ALTER TABLE franchises
ALTER COLUMN frch_price_buyout TYPE DOUBLE PRECISION,
ALTER COLUMN frch_price_yearly TYPE DOUBLE PRECISION;

ALTER TABLE order_franchises
ALTER COLUMN orfi_tax TYPE DOUBLE PRECISION,
ALTER COLUMN orfi_subtotal TYPE DOUBLE PRECISION;
