// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cart struct {
	CartID         int32            `json:"cart_id"`
	CartUserID     *int32           `json:"cart_user_id"`
	CartFrID       *int32           `json:"cart_fr_id"`
	CartStartDate  pgtype.Timestamp `json:"cart_start_date"`
	CartEndDate    pgtype.Timestamp `json:"cart_end_date"`
	CartQty        *int32           `json:"cart_qty"`
	CartPrice      *float64         `json:"cart_price"`
	CartTotalPrice *float64         `json:"cart_total_price"`
	CartModified   pgtype.Timestamp `json:"cart_modified"`
	CartStatus     *string          `json:"cart_status"`
	CartCartID     *int32           `json:"cart_cart_id"`
}

type Category struct {
	CateID   int32   `json:"cate_id"`
	CateName *string `json:"cate_name"`
}

type Franchise struct {
	FrchID          int32            `json:"frch_id"`
	FrchName        *string          `json:"frch_name"`
	FrchDesc        *string          `json:"frch_desc"`
	FrchPriceBuyout *float64         `json:"frch_price_buyout"`
	FrchPriceYearly *float64         `json:"frch_price_yearly"`
	FrchModified    pgtype.Timestamp `json:"frch_modified"`
	FrchCateID      *int32           `json:"frch_cate_id"`
}

type FranchisesImage struct {
	FrimID       int32   `json:"frim_id"`
	FrimFilename *string `json:"frim_filename"`
	FrimDefault  *string `json:"frim_default"`
	FrimFrchID   *int32  `json:"frim_frch_id"`
}

type OrderFranchise struct {
	OrfiID         int32       `json:"orfi_id"`
	OrfiPurchaseNo *string     `json:"orfi_purchase_no"`
	OrfiTax        *float64    `json:"orfi_tax"`
	OrfiSubtotal   *float64    `json:"orfi_subtotal"`
	OrfiPatrxNo    *string     `json:"orfi_patrx_no"`
	OrfiType       *string     `json:"orfi_type"`
	OrfiModified   pgtype.Date `json:"orfi_modified"`
	OrfiUserID     *int32      `json:"orfi_user_id"`
}

type OrderFranchisesDetail struct {
	OfdeID         int32            `json:"ofde_id"`
	OfdeStartDate  pgtype.Timestamp `json:"ofde_start_date"`
	OfdeEndDate    pgtype.Timestamp `json:"ofde_end_date"`
	OfdeQtyUnit    *int32           `json:"ofde_qty_unit"`
	OfdePrice      *float64         `json:"ofde_price"`
	OfdeTotalPrice *float64         `json:"ofde_total_price"`
	OfdeOrfiID     *int32           `json:"ofde_orfi_id"`
	OfdeFrchID     *int32           `json:"ofde_frch_id"`
}

type User struct {
	UserID       int32   `json:"user_id"`
	UserName     *string `json:"user_name"`
	UserPassword *string `json:"user_password"`
	UserEmail    *string `json:"user_email"`
	UserPhone    *string `json:"user_phone"`
	UserToken    *string `json:"user_token"`
}
